name: ServerPlugin
version: 1.0.0
main: net.minenite.serverplugin.ServerPlugin
api-version: '1.21'
author: icedmoca
description: Core plugin for the network - friends, friendly fire and cross-server travel.

commands:
  friend:
    description: Core plugin for the network - friends, friendly fire and cross-server travel.
    usage: /friend [username]
    aliases: [friends]
  join:
    description: Core plugin for the network - friends, friendly fire and cross-server travel.
    usage: /join <username>
